.TH CSVCOUNT "1" "02 June 2007" "" "csvutils"
.SH NAME
csvcount \- print the number of fields and rows in a CSV file
.SH SYNOPSIS
.nf
.ft B
csvcount [OPTION]... [FILE]...
.LP
.fi
.SH DESCRIPTION
.ft
.ft
.fi
Read CSV data from standard input or one or more specified files and
print the number of fields and rows encountered.

.TP
\fB-d\fR, \fB--delimiter\fR=\fIDELIM\fR
Use \fIDELIM\fP instead of the comma character as the delimiter character
.TP
\fB-q\fR, \fB--quote\fR=\fIQUOTE\fR
Use \fIQUOTE\fR instead of double quote as the quote character
.TP
\fB-f\fR, \fB--fields\fR
Print only the number of fields in each file
.TP
\fB-r\fR, \fB--rows\fR
Print only the number of rows in each file
.TP
\fB--help\fR
Display a help message and exit
.TP
\fB--version\fR
Print version information to stderr and exit

.SH AUTHOR
Written by Robert Gamble.

.SH BUGS
Please send questions, comments, bugs, etc. to: rgamble@sourceforge.net

.SH COPYRIGHT
.nf
Copyright © 2007 Robert Gamble
.fi
This is free software.  You may redistribute copies of it under the terms of the
GNU General Public License <http://www.gnu.org/licenses/gpl.html>.  There is NO
WARRANTY, to the extent permitted by law.

.SH SEE ALSO
csvcount(1), csvcheck(1), csvfix(1), csvcut(1), csvgrep(1), csvbreak(1)

