.TH CSVGREP "1" "16 June 2007" "" "csvutils"
.SH NAME
csvgrep \- print selected fields from CSV files
.SH SYNOPSIS
.nf
.ft B
csvgrep [OPTION]... PATTERN [FILE]...
.LP
.fi
.SH DESCRIPTION
.ft
.ft
.fi
Read CSV data from standard input or \fIFILE\fRs searching for \fIPATTERN\fR in the specified fields and print matching rows to standard output.
.TP
\fB-d\fR, \fB--delimiter\fR=\fIDELIM\fR
Use \fIDELIM\fP instead of the comma character as the delimiter character
.TP
\fB-f\fR, \fB--fields\fR=\fIFIELD-LIST\fR
\fIFIELD-LIST\fR is a comma seperated list of fields or field ranges to search,
fields may be specified by number starting at 1 or by field name.  A field name must contain at least
one non-digit character.  Ranges may also be used and consist of two field numbers or names seperated
by a hyphen.  For example, the field list \fB"1,3,5-City"\fR would select the first and third fields as well
as all fields between the fifth field and the field named "City" inclusive.  When using field names it
is assumed that the first non-empty record contains a header with field names that match the names
used in the field list, if any field names cannot be resolved from the first record an error will occur.
If the same field name occurs multiple times in the header record, the first one seen is the one used.
.TP
\fB-H\fR, \fB--with-filename\fR
prefix matches with the filename and a colon
This option is implied when matching multiple files with the -c option
.TP
\fB-h\fR, \fB--no-filename\fR
suppress filename prefixing
.TP
\fB-l\fR, \fB--files-with-matches\fR
Suppress normal output and print only the names of files that would have
produced output
.TP
\fB-L\fR, \fB--files-without-match\fR
Suppress normal output and print only the names of files that would
have resulted in no output
.TP
\fB-P\fR, \fB--perl-regexp\fR
interpret \fIPATTERN\fR as a perl-compatible regular expression (requires pcre).
See http://perldoc.perl.org/perlre.html for expression syntax
.TP
\fB-i\fR, \fB--ignore-case\fR
perform case insensitive match
.TP
\fB-v\fR, \fB--invert-match\fR
select all records that do not match pattern
.TP
\fB-n\fR, \fB--record-number\fR
prefix matched records with record numbers
.TP
\fB-F\fR, \fB--fixed-strings\fR
interpret pattern as a fixed literal string instead of a regular expression
.TP
\fB-r\fR, \fB--reresolve-fields\fR
re-resolve the field names specified for each file processed instead of using the positions
resolved from the first file.  By default, when processing multiple files, only the header from the
first file is used to map the field names to field numbers.  This option will cause csvcut to attempt
to re-aquire this information for each file and will cause an error if any of the files fails to
contain the neccessary information to do so.
.TP
\fB-s\fR, \fB--strict\fR
enforce strict mode, mal-formed CSV files will cause an error
.TP
\fB-c\fR, \fB--count\fR
print only a count of matching records
.TP
\fB-q\fR, \fB--quote\fR=\fIQUOTE\fR
Use \fIQUOTE\fR instead of double quote as the quote character
.TP
\fB--print-header\fR
print CSV header, this is the default when non-numeric field names are specified
.TP
\fB--no-print-header\fR
do not print a header
.TP
\fB--help\fR
Display a help message and exit
.TP
\fB--version\fR
Print version information to stderr and exit

.SH LIMITATIONS
Matching with POSIX regular expressions (-E) or fixed text (-F) will not match data after the first null character of a field, this limitation is not present when using Perl Compatible Regular Expressions (-P).

.SH AUTHOR
Written by Robert Gamble.

.SH BUGS
Please send questions, comments, bugs, etc. to: rgamble@sourceforge.net

.SH COPYRIGHT
.nf
Copyright © 2007 Robert Gamble
.fi
This is free software.  You may redistribute copies of it under the terms of the
GNU General Public License <http://www.gnu.org/licenses/gpl.html>.  There is NO
WARRANTY, to the extent permitted by law.

.SH SEE ALSO
csvcount(1), csvcheck(1), csvfix(1), csvcut(1), csvgrep(1), csvbreak(1)

